backend:
  name: github
  repo: kirillmazin/gatsby-netlify

media_folder: static/assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    extenstion: json
    format: json
    fields:
      - { name: project_name, label: Project Name }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: project_title, label: Project Title }
      - { name: hero_image, label: Hero image, widget: "image"}
  - name: case-study
    label: Case Study
    folder: case-study
    create: true
    delete: true
    slug: "{{slug}}"
    extenstion: json
    format: json
    fields:
      - { name: project_name, label: Project Name }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: project_title, label: Project Title }
      - { name: hero_image, label: Hero image, widget: "image"}

      - label: "Testimonials"
        name: "testimonials"
        widget: "list"
        fields:
          - {label: Quote, name: quote, widget: string, default: "Everything is awesome!"}
          - label: Author
            name: author
            widget: object
            fields:
              - {label: Name, name: name, widget: string, default: "Emmet"}
              - {label: Avatar, name: avatar, widget: image}
