backend:
  name: github
  repo: kirillmazin/gatsby-netlify

media_folder: static/assets

collections:
  - label: "Blog"
    name: "blog"
    folder: "_posts/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Case study"
    name: "case_study"
    folder: "_posts/case_study"
    create: true
    fields:
      - {label: "Case study name", name: "case_study_index", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - label: "Image grid"
        name: "case_study_image_grid"
        widget: "list"
        fields:
            - {label: "Image alt", name: "image_alt", widget: "string"}
            - {label: "Image", name: "image", widget: "image"}
      - {label: "Service", name: "service", widget: "string"}
  - label: "Case study list"
    name: "case_study_list"
    folder: "_posts/case_study_list"
    create: true
    fields:
      - {label: "Case study item", name: "case_study_item", widget: "relation", collection: "case_study", searchFields:["name"],valueField:"name"}
